[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multi_wallet = "revibJxgb7X4j3tFT4n1oDNqZwLS28snWpPdwLRm7hb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/multi-wallet/index.ts"
